-- DropX 2.0 — 017 brand + specs backfill (generated — do not hand-edit)
-- Source: lists/starter-products.csv via scripts/build-seed.py
-- Fills brand + specs for catalog rows inserted by an older 008.
-- Idempotent: plain UPDATEs by slug.

update public.products set brand = 'Deli', specs = '{"brand": "Deli", "tip": "HB", "pack_size": "12", "weight": "18 g"}'::jsonb where slug = 'deli-graphite-pencils-12-pack';
update public.products set brand = 'Apsara', specs = '{"brand": "Apsara", "tip": "HB", "pack_size": "10", "weight": "55 g"}'::jsonb where slug = 'apsara-platinum-pencils-10-pack';
update public.products set brand = 'M&G', specs = '{"brand": "M&G", "tip": "2 mm", "pack_size": "5", "weight": "51 g"}'::jsonb where slug = 'mg-blue-ball-pens-5-pack';
update public.products set brand = 'Cello', specs = '{"brand": "Cello", "tip": "2 mm", "pack_size": "1", "weight": "47 g"}'::jsonb where slug = 'cello-butterflow-pen-set-10';
update public.products set brand = 'Deli', specs = '{"brand": "Deli", "tip": "0.5 mm", "pack_size": "6", "weight": "43 g"}'::jsonb where slug = 'deli-gel-pens-05mm-6-pack';
update public.products set brand = 'Faber-Castell', specs = '{"brand": "Faber-Castell", "tip": "2 mm", "pack_size": "4", "weight": "39 g"}'::jsonb where slug = 'faber-castell-highlighters-4-set';
update public.products set brand = 'Deli', specs = '{"brand": "Deli", "size": "A5", "pages": "220", "paper": "80 GSM", "weight": "221 g"}'::jsonb where slug = 'deli-sticky-notes-4-pad-set';
update public.products set brand = 'M&G', specs = '{"brand": "M&G", "material": "PP plastic", "weight": "138 g"}'::jsonb where slug = 'mg-correction-tape-2-pack';
update public.products set brand = 'Kangaro', specs = '{"brand": "Kangaro", "material": "PP plastic", "weight": "175 g"}'::jsonb where slug = 'kangaro-stapler-plus-pins-combo';
update public.products set brand = 'Deli', specs = '{"brand": "Deli", "material": "PP plastic", "weight": "212 g"}'::jsonb where slug = 'deli-2-hole-paper-punch';
update public.products set brand = 'Kores', specs = '{"brand": "Kores", "material": "Metal + plastic", "weight": "249 g"}'::jsonb where slug = 'kores-glue-sticks-3-pack';
update public.products set brand = 'Deli', specs = '{"brand": "Deli", "material": "Metal + plastic", "weight": "85 g"}'::jsonb where slug = 'deli-craft-scissors-17cm';
update public.products set brand = 'Deli', specs = '{"brand": "Deli", "material": "Metal + plastic", "weight": "122 g"}'::jsonb where slug = 'deli-steel-ruler-30cm';
update public.products set brand = 'M&G', specs = '{"brand": "M&G", "material": "Metal + plastic", "weight": "159 g"}'::jsonb where slug = 'mg-geometry-box-8-piece';
update public.products set brand = 'Deli', specs = '{"brand": "Deli", "size": "A5", "pages": "220", "paper": "80 GSM", "weight": "154 g"}'::jsonb where slug = 'deli-spiral-notebook-a5-200-page';
update public.products set brand = 'Deli', specs = '{"brand": "Deli", "size": "A4", "pages": "240", "paper": "80 GSM", "weight": "191 g"}'::jsonb where slug = 'deli-kraft-register-a4-256-page';
update public.products set brand = 'M&G', specs = '{"brand": "M&G", "size": "A5", "pages": "100", "paper": "80 GSM", "weight": "228 g"}'::jsonb where slug = 'mg-dot-grid-notebooks-a5-duo';
update public.products set brand = 'Faber-Castell', specs = '{"brand": "Faber-Castell", "size": "A4", "pages": "120", "paper": "80 GSM", "weight": "144 g"}'::jsonb where slug = 'faber-castell-drawing-book-a4';
update public.products set brand = 'Camlin', specs = '{"brand": "Camlin", "tip": "HB", "pack_size": "24", "weight": "28 g"}'::jsonb where slug = 'camlin-colour-pencils-24-set';
update public.products set brand = 'Deli', specs = '{"brand": "Deli", "tip": "2 mm", "pack_size": "24", "weight": "24 g"}'::jsonb where slug = 'deli-wax-crayons-24-set';
update public.products set brand = 'Doms', specs = '{"brand": "Doms", "tip": "2 mm", "pack_size": "12", "weight": "20 g"}'::jsonb where slug = 'doms-sketch-markers-12-set';
update public.products set brand = 'Faber-Castell', specs = '{"brand": "Faber-Castell", "material": "Metal + plastic", "weight": "254 g"}'::jsonb where slug = 'faber-castell-watercolours-24';
update public.products set brand = 'Deli', specs = '{"brand": "Deli", "material": "Metal + plastic", "weight": "90 g"}'::jsonb where slug = 'deli-acrylic-paint-12-tubes';
update public.products set brand = 'Deli', specs = '{"brand": "Deli", "tip": "2 mm", "pack_size": "10", "weight": "49 g"}'::jsonb where slug = 'deli-artist-brushes-10-piece';
update public.products set brand = 'Casio', specs = '{"brand": "Casio", "functions": "12-digit", "power": "Solar + battery", "weight": "124 g"}'::jsonb where slug = 'casio-mj-12da-desktop-calculator';
update public.products set brand = 'Deli', specs = '{"brand": "Deli", "functions": "240", "power": "Solar + battery", "weight": "100 g"}'::jsonb where slug = 'deli-scientific-calculator-240-function';
update public.products set brand = 'No Brand', specs = '{"brand": "No Brand", "material": "PP plastic", "weight": "238 g"}'::jsonb where slug = 'exam-clipboard-a4-with-cover';
update public.products set brand = 'Deli', specs = '{"brand": "Deli", "material": "PP plastic", "weight": "275 g"}'::jsonb where slug = 'deli-expanding-file-13-pocket';
update public.products set brand = 'M&G', specs = '{"brand": "M&G", "material": "PP plastic", "weight": "111 g"}'::jsonb where slug = 'mg-button-folders-a4-5-pack';
update public.products set brand = 'Deli', specs = '{"brand": "Deli", "material": "Canvas", "weight": "148 g"}'::jsonb where slug = 'deli-document-bag-with-handle';
update public.products set brand = 'Deli', specs = '{"brand": "Deli", "material": "Metal + plastic", "weight": "185 g"}'::jsonb where slug = 'deli-mesh-desk-organizer';
update public.products set brand = 'M&G', specs = '{"brand": "M&G", "tip": "HB", "pack_size": "1", "weight": "58 g"}'::jsonb where slug = 'mg-canvas-pencil-pouch';
update public.products set brand = 'Deli', specs = '{"brand": "Deli", "tip": "HB", "pack_size": "1", "weight": "54 g"}'::jsonb where slug = 'deli-multi-pocket-pencil-case';
update public.products set brand = 'Kores', specs = '{"brand": "Kores", "tip": "2 mm", "pack_size": "4", "weight": "50 g"}'::jsonb where slug = 'kores-whiteboard-markers-4-set';
update public.products set brand = 'Deli', specs = '{"brand": "Deli", "material": "PP plastic", "weight": "132 g"}'::jsonb where slug = 'deli-exam-board-a3-with-clip';
update public.products set brand = 'Camlin', specs = '{"brand": "Camlin", "size": "A5", "pages": "160", "paper": "80 GSM", "weight": "205 g"}'::jsonb where slug = 'camlin-chart-papers-10-sheet';
update public.products set brand = 'Deli', specs = '{"brand": "Deli", "material": "Metal + plastic", "weight": "206 g"}'::jsonb where slug = 'deli-page-flags-5-colour-set';
update public.products set brand = 'M&G', specs = '{"brand": "M&G", "material": "PP plastic", "weight": "243 g"}'::jsonb where slug = 'mg-binder-clips-25-pack';
update public.products set brand = 'Deli', specs = '{"brand": "Deli", "tip": "2 mm", "pack_size": "2", "weight": "30 g"}'::jsonb where slug = 'deli-tape-dispenser-plus-2-rolls';
update public.products set brand = 'Faber-Castell', specs = '{"brand": "Faber-Castell", "tip": "2 mm", "pack_size": "1", "weight": "26 g"}'::jsonb where slug = 'faber-castell-eraser-sharpener-duo';
update public.products set brand = 'Ultima', specs = '{"brand": "Ultima", "driver": "10 mm", "battery": "20 h playtime", "bluetooth": "5.3", "warranty": "6 months"}'::jsonb where slug = 'ultima-boom-211-tws-earbuds';
update public.products set brand = 'Redmi', specs = '{"brand": "Redmi", "compatibility": "Universal", "material": "ABS + aluminium", "warranty": "6 months", "weight": "128 g"}'::jsonb where slug = 'redmi-buds-basic-2';
update public.products set brand = 'Anker', specs = '{"brand": "Anker", "driver": "10 mm", "battery": "30 h playtime", "bluetooth": "5.3", "warranty": "6 months"}'::jsonb where slug = 'anker-soundcore-p20i-earbuds';
update public.products set brand = 'Boat', specs = '{"brand": "Boat", "compatibility": "Universal", "material": "ABS + aluminium", "warranty": "6 months", "weight": "202 g"}'::jsonb where slug = 'boat-airdopes-161-tws';
update public.products set brand = 'Oraimo', specs = '{"brand": "Oraimo", "compatibility": "Universal", "material": "ABS + aluminium", "warranty": "6 months", "weight": "78 g"}'::jsonb where slug = 'oraimo-spacebuds-neo-tws';
update public.products set brand = 'Hoco', specs = '{"brand": "Hoco", "driver": "10 mm", "battery": "23 h playtime", "bluetooth": "5.3", "warranty": "6 months"}'::jsonb where slug = 'hoco-eq34-plus-earbuds';
update public.products set brand = 'Lenovo', specs = '{"brand": "Lenovo", "driver": "10 mm", "battery": "28 h playtime", "bluetooth": "5.3", "warranty": "6 months"}'::jsonb where slug = 'lenovo-he05-neckband';
update public.products set brand = 'Remax', specs = '{"brand": "Remax", "compatibility": "Universal", "material": "ABS + aluminium", "warranty": "6 months", "weight": "189 g"}'::jsonb where slug = 'remax-type-c-earphones';
update public.products set brand = 'Oraimo', specs = '{"brand": "Oraimo", "compatibility": "Universal", "material": "ABS + aluminium", "warranty": "6 months", "weight": "65 g"}'::jsonb where slug = 'oraimo-conch-wired-earphones';
update public.products set brand = 'Baseus', specs = '{"brand": "Baseus", "length": "1 m", "output": "60W"}'::jsonb where slug = 'baseus-60w-usb-c-cable-1m';
update public.products set brand = 'Ugreen', specs = '{"brand": "Ugreen", "length": "2 m", "output": "60W"}'::jsonb where slug = 'ugreen-braided-usb-c-cable-2m';
update public.products set brand = 'Remax', specs = '{"brand": "Remax", "length": "1 m", "output": "60W"}'::jsonb where slug = 'remax-3-in-1-charging-cable';
update public.products set brand = 'Aukey', specs = '{"brand": "Aukey", "length": "1 m", "output": "100W"}'::jsonb where slug = 'aukey-100w-c-to-c-cable';
update public.products set brand = 'Anker', specs = '{"brand": "Anker", "output": "20W", "ports": "2", "warranty": "12 months"}'::jsonb where slug = 'anker-20w-usb-c-charger';
update public.products set brand = 'Aukey', specs = '{"brand": "Aukey", "output": "30W", "ports": "2", "warranty": "12 months"}'::jsonb where slug = 'aukey-30w-wall-charger';
update public.products set brand = 'Baseus', specs = '{"brand": "Baseus", "capacity": "10000 mAh", "output": "22.5W", "warranty": "6 months"}'::jsonb where slug = 'baseus-mini-power-bank-10k';
update public.products set brand = 'Oraimo', specs = '{"brand": "Oraimo", "capacity": "10000 mAh", "output": "22.5W", "warranty": "6 months"}'::jsonb where slug = 'oraimo-10k-power-bank-15w';
update public.products set brand = 'Mi', specs = '{"brand": "Mi", "output": "18W", "ports": "2", "warranty": "12 months"}'::jsonb where slug = 'mi-18w-charger-plus-cable-combo';
update public.products set brand = 'Ugreen', specs = '{"brand": "Ugreen", "compatibility": "Universal", "material": "ABS + aluminium", "warranty": "6 months", "weight": "113 g"}'::jsonb where slug = 'ugreen-4-port-usb-hub';
update public.products set brand = 'HP', specs = '{"brand": "HP", "compatibility": "Universal", "material": "ABS + aluminium", "warranty": "6 months", "weight": "150 g"}'::jsonb where slug = 'hp-wired-optical-mouse';
update public.products set brand = 'Lenovo', specs = '{"brand": "Lenovo", "compatibility": "Universal", "material": "ABS + aluminium", "warranty": "6 months", "weight": "187 g"}'::jsonb where slug = 'lenovo-24g-wireless-mouse';
update public.products set brand = 'No Brand', specs = '{"brand": "No Brand", "compatibility": "Universal", "material": "ABS + aluminium", "warranty": "6 months", "weight": "63 g"}'::jsonb where slug = 'foldable-laptop-stand-aluminium';
update public.products set brand = 'Baseus', specs = '{"brand": "Baseus", "compatibility": "Universal", "material": "ABS + aluminium", "warranty": "6 months", "weight": "100 g"}'::jsonb where slug = 'baseus-adjustable-phone-stand';
update public.products set brand = 'Ugreen', specs = '{"brand": "Ugreen", "compatibility": "Universal", "material": "ABS + aluminium", "warranty": "6 months", "weight": "137 g"}'::jsonb where slug = 'ugreen-14-inch-laptop-sleeve';
update public.products set brand = 'Oraimo', specs = '{"brand": "Oraimo", "compatibility": "Universal", "material": "ABS + aluminium", "warranty": "6 months", "weight": "174 g"}'::jsonb where slug = 'oraimo-grip-stand-duo';
update public.products set brand = 'SanDisk', specs = '{"brand": "SanDisk", "compatibility": "Universal", "material": "ABS + aluminium", "warranty": "6 months", "weight": "211 g"}'::jsonb where slug = 'sandisk-64gb-usb-30-drive';
update public.products set brand = 'Samsung', specs = '{"brand": "Samsung", "compatibility": "Universal", "material": "ABS + aluminium", "warranty": "6 months", "weight": "87 g"}'::jsonb where slug = 'samsung-usb-c-otg-adapter';
update public.products set brand = 'Mi', specs = '{"brand": "Mi", "power": "USB 5V", "modes": "3", "weight": "346 g"}'::jsonb where slug = 'mi-rechargeable-desk-lamp';
update public.products set brand = 'Ultima', specs = '{"brand": "Ultima", "driver": "10 mm", "battery": "28 h playtime", "bluetooth": "5.3", "warranty": "6 months"}'::jsonb where slug = 'ultima-nova-mini-speaker';
update public.products set brand = 'Boat', specs = '{"brand": "Boat", "driver": "10 mm", "battery": "33 h playtime", "bluetooth": "5.3", "warranty": "6 months"}'::jsonb where slug = 'boat-5w-stone-speaker';
update public.products set brand = 'Zebronics', specs = '{"brand": "Zebronics", "driver": "13 mm", "battery": "38 h playtime", "bluetooth": "5.3", "warranty": "6 months"}'::jsonb where slug = 'zebronics-thunder-headphones';
update public.products set brand = 'Hoco', specs = '{"brand": "Hoco", "display": "2.0 inch", "battery": "7 days standby", "water_resistance": "IP67", "warranty": "12 months"}'::jsonb where slug = 'hoco-y19-smart-watch';
update public.products set brand = 'Oraimo', specs = '{"brand": "Oraimo", "display": "2.0 inch", "battery": "7 days standby", "water_resistance": "IP67", "warranty": "12 months"}'::jsonb where slug = 'oraimo-watch-5-lite';
update public.products set brand = 'Noise', specs = '{"brand": "Noise", "driver": "10 mm", "battery": "31 h playtime", "bluetooth": "5.3", "warranty": "6 months"}'::jsonb where slug = 'noise-twist-neckband';
update public.products set brand = 'Baseus', specs = '{"brand": "Baseus", "driver": "10 mm", "battery": "36 h playtime", "bluetooth": "5.3", "warranty": "6 months"}'::jsonb where slug = 'baseus-encok-wired-earbuds';
update public.products set brand = 'Remax', specs = '{"brand": "Remax", "capacity": "20000 mAh", "output": "22.5W", "warranty": "6 months"}'::jsonb where slug = 'remax-20000mah-power-bank';
update public.products set brand = 'Anker', specs = '{"brand": "Anker", "length": "1 m", "output": "60W"}'::jsonb where slug = 'anker-cable-organizer-3-pack';
update public.products set brand = 'Mi', specs = '{"brand": "Mi", "compatibility": "Universal", "material": "ABS + aluminium", "warranty": "6 months", "weight": "172 g"}'::jsonb where slug = 'mi-wifi-extender-n300';
update public.products set brand = 'Hoco', specs = '{"brand": "Hoco", "compatibility": "Universal", "material": "ABS + aluminium", "warranty": "6 months", "weight": "209 g"}'::jsonb where slug = 'hoco-360-phone-holder';
update public.products set brand = 'Baseus', specs = '{"brand": "Baseus", "compatibility": "Universal", "material": "ABS + aluminium", "warranty": "6 months", "weight": "85 g"}'::jsonb where slug = 'baseus-screen-cleaner-kit';
update public.products set brand = 'Goldstar', specs = '{"brand": "Goldstar", "upper": "Canvas", "sole": "Anti-skid rubber", "weight": "709 g"}'::jsonb where slug = 'goldstar-classic-white-sneakers';
update public.products set brand = 'Goldstar', specs = '{"brand": "Goldstar", "upper": "Knit + synthetic", "sole": "Anti-skid rubber", "weight": "746 g"}'::jsonb where slug = 'goldstar-grey-running-shoes';
update public.products set brand = 'No Brand', specs = '{"brand": "No Brand", "upper": "Canvas", "sole": "Anti-skid rubber", "weight": "783 g"}'::jsonb where slug = 'air-style-white-sneakers';
update public.products set brand = 'Caliber', specs = '{"brand": "Caliber", "upper": "Knit + synthetic", "sole": "Anti-skid rubber", "weight": "820 g"}'::jsonb where slug = 'caliber-black-street-sneakers';
update public.products set brand = 'No Brand', specs = '{"brand": "No Brand", "material": "180 GSM cotton", "fit": "Regular", "care": "Machine wash cold"}'::jsonb where slug = 'cotton-t-shirts-3-pack';
update public.products set brand = 'No Brand', specs = '{"brand": "No Brand", "material": "180 GSM cotton", "fit": "Loose", "care": "Machine wash cold"}'::jsonb where slug = 'oversized-graphic-tee-ember';
update public.products set brand = 'No Brand', specs = '{"brand": "No Brand", "material": "180 GSM cotton", "fit": "Regular", "care": "Machine wash cold"}'::jsonb where slug = 'polo-collar-tee-navy';
update public.products set brand = 'No Brand', specs = '{"brand": "No Brand", "material": "180 GSM cotton", "fit": "Regular", "care": "Machine wash cold"}'::jsonb where slug = 'full-sleeve-henley-tee';
update public.products set brand = 'No Brand', specs = '{"brand": "No Brand", "material": "480 GSM fleece", "fit": "Regular", "care": "Machine wash cold"}'::jsonb where slug = 'antipilling-hoodie-charcoal';
update public.products set brand = 'No Brand', specs = '{"brand": "No Brand", "material": "480 GSM fleece", "fit": "Regular", "care": "Machine wash cold"}'::jsonb where slug = 'half-zip-hoodie-black';
update public.products set brand = 'No Brand', specs = '{"brand": "No Brand", "material": "480 GSM fleece", "fit": "Regular", "care": "Machine wash cold"}'::jsonb where slug = 'fleece-sweatshirt-dirtywash';
update public.products set brand = 'No Brand', specs = '{"brand": "No Brand", "material": "Denim", "fit": "Regular", "care": "Machine wash cold"}'::jsonb where slug = 'classic-wash-denim-jacket';
update public.products set brand = 'No Brand', specs = '{"brand": "No Brand", "material": "Stretch denim", "fit": "Slim", "care": "Machine wash cold"}'::jsonb where slug = 'slim-stretch-jeans-indigo';
update public.products set brand = 'No Brand', specs = '{"brand": "No Brand", "material": "Cotton blend", "fit": "Regular", "care": "Machine wash cold"}'::jsonb where slug = 'olive-cargo-joggers';
update public.products set brand = 'No Brand', specs = '{"brand": "No Brand", "material": "Cotton blend", "fit": "Regular", "care": "Machine wash cold"}'::jsonb where slug = 'floral-cotton-kurti';
update public.products set brand = 'No Brand', specs = '{"brand": "No Brand", "material": "Cotton blend", "fit": "Regular", "care": "Machine wash cold"}'::jsonb where slug = 'summer-midi-dress';
update public.products set brand = 'No Brand', specs = '{"brand": "No Brand", "material": "180 GSM cotton", "fit": "Regular", "care": "Machine wash cold"}'::jsonb where slug = 'flannel-check-shirt';
update public.products set brand = 'No Brand', specs = '{"brand": "No Brand", "material": "180 GSM cotton", "fit": "Regular", "care": "Machine wash cold"}'::jsonb where slug = 'white-oxford-casual-shirt';
update public.products set brand = 'No Brand', specs = '{"brand": "No Brand", "material": "Cotton blend", "fit": "Regular", "care": "Machine wash cold"}'::jsonb where slug = 'gym-shorts-2-pack';
update public.products set brand = 'No Brand', specs = '{"brand": "No Brand", "material": "Cotton blend", "care": "Wipe clean"}'::jsonb where slug = 'ankle-socks-5-pair-set';
update public.products set brand = 'No Brand', specs = '{"brand": "No Brand", "material": "Mixed materials", "care": "Wipe clean"}'::jsonb where slug = 'everest-embroidered-cap';
update public.products set brand = 'No Brand', specs = '{"brand": "No Brand", "material": "Cotton blend", "care": "Wipe clean"}'::jsonb where slug = 'woollen-winter-beanie';
update public.products set brand = 'No Brand', specs = '{"brand": "No Brand", "material": "Mixed materials", "care": "Wipe clean"}'::jsonb where slug = 'reversible-leather-belt';
update public.products set brand = 'No Brand', specs = '{"brand": "No Brand", "material": "Mixed materials", "care": "Wipe clean"}'::jsonb where slug = 'military-canvas-belt';
update public.products set brand = 'No Brand', specs = '{"brand": "No Brand", "material": "Mixed materials", "care": "Wipe clean"}'::jsonb where slug = 'tan-bifold-wallet';
update public.products set brand = 'No Brand', specs = '{"brand": "No Brand", "material": "Mixed materials", "care": "Wipe clean"}'::jsonb where slug = 'slim-card-holder';
update public.products set brand = 'No Brand', specs = '{"brand": "No Brand", "material": "UV400 polycarbonate", "care": "Wipe clean"}'::jsonb where slug = 'aviator-sunglasses-uv400';
update public.products set brand = 'No Brand', specs = '{"brand": "No Brand", "material": "UV400 polycarbonate", "care": "Wipe clean"}'::jsonb where slug = 'retro-round-sunglasses';
update public.products set brand = 'No Brand', specs = '{"brand": "No Brand", "capacity": "25 L", "material": "Water-resistant polyester", "weight": "624 g"}'::jsonb where slug = 'school-backpack-25l';
update public.products set brand = 'No Brand', specs = '{"brand": "No Brand", "capacity": "25 L", "material": "Water-resistant polyester", "weight": "661 g"}'::jsonb where slug = 'usb-laptop-backpack-15-inch';
update public.products set brand = 'No Brand', specs = '{"brand": "No Brand", "capacity": "12 L", "material": "Water-resistant polyester", "weight": "698 g"}'::jsonb where slug = 'drawstring-gym-bag';
update public.products set brand = 'No Brand', specs = '{"brand": "No Brand", "movement": "Quartz", "strap": "Genuine leather", "water_resistance": "3 ATM"}'::jsonb where slug = 'leather-strap-analog-watch';
update public.products set brand = 'No Brand', specs = '{"brand": "No Brand", "movement": "Quartz", "strap": "Silicone", "water_resistance": "3 ATM"}'::jsonb where slug = 'digital-sports-watch';
update public.products set brand = 'No Brand', specs = '{"brand": "No Brand", "material": "Metal alloy", "care": "Wipe clean"}'::jsonb where slug = 'bead-bracelets-set-of-3';
update public.products set brand = 'No Brand', specs = '{"brand": "No Brand", "material": "Metal alloy", "care": "Wipe clean"}'::jsonb where slug = 'silver-stud-earrings-6-pair';
update public.products set brand = 'No Brand', specs = '{"brand": "No Brand", "upper": "Knit + synthetic", "sole": "Anti-skid rubber", "weight": "699 g"}'::jsonb where slug = 'anti-skid-slides';
update public.products set brand = 'No Brand', specs = '{"brand": "No Brand", "upper": "Knit + synthetic", "sole": "Anti-skid rubber", "weight": "736 g"}'::jsonb where slug = 'comfort-flip-flops';
update public.products set brand = 'No Brand', specs = '{"brand": "No Brand", "material": "Cotton blend", "care": "Wipe clean"}'::jsonb where slug = 'wool-blend-winter-muffler';
update public.products set brand = 'No Brand', specs = '{"brand": "No Brand", "material": "Cotton blend", "care": "Wipe clean"}'::jsonb where slug = 'winter-gloves-touchscreen-pair';
update public.products set brand = 'No Brand', specs = '{"brand": "No Brand", "material": "Denim", "fit": "Regular", "care": "Machine wash cold"}'::jsonb where slug = 'packable-rain-jacket';
update public.products set brand = 'No Brand', specs = '{"brand": "No Brand", "capacity": "1 L", "material": "SS304 stainless steel", "insulation": "12 h hot / 24 h cold"}'::jsonb where slug = 'steel-vacuum-flask-1l';
update public.products set brand = 'No Brand', specs = '{"brand": "No Brand", "capacity": "750 ML", "material": "Ceramic", "insulation": "Hand wash"}'::jsonb where slug = 'motivational-sip-bottle-750ml';
update public.products set brand = 'No Brand', specs = '{"brand": "No Brand", "capacity": "350 ML", "material": "Ceramic", "insulation": "Hand wash"}'::jsonb where slug = 'ceramic-mugs-350ml-duo';
update public.products set brand = 'No Brand', specs = '{"brand": "No Brand", "capacity": "750 ml", "material": "Ceramic", "insulation": "Hand wash"}'::jsonb where slug = 'colour-changing-magic-mug';
update public.products set brand = 'No Brand', specs = '{"brand": "No Brand", "material": "Mixed materials", "dimensions": "Standard", "care": "Wipe clean"}'::jsonb where slug = 'steel-lunch-box-3-layer';
update public.products set brand = 'No Brand', specs = '{"brand": "No Brand", "material": "Mixed materials", "dimensions": "Standard", "care": "Wipe clean"}'::jsonb where slug = 'tiffin-carrier-4-tier-round';
update public.products set brand = 'No Brand', specs = '{"brand": "No Brand", "material": "Mixed materials", "dimensions": "Standard", "care": "Wipe clean"}'::jsonb where slug = 'natural-canvas-tote';
update public.products set brand = 'No Brand', specs = '{"brand": "No Brand", "material": "Mixed materials", "dimensions": "Standard", "care": "Wipe clean"}'::jsonb where slug = 'foldable-shopping-bag';
update public.products set brand = 'No Brand', specs = '{"brand": "No Brand", "material": "Mixed materials", "dimensions": "Standard", "care": "Wipe clean"}'::jsonb where slug = 'windproof-auto-umbrella';
update public.products set brand = 'No Brand', specs = '{"brand": "No Brand", "material": "Mixed materials", "dimensions": "Standard", "care": "Wipe clean"}'::jsonb where slug = 'mini-capsule-umbrella';
update public.products set brand = 'No Brand', specs = '{"brand": "No Brand", "material": "Mixed materials", "dimensions": "10 m", "care": "Wipe clean"}'::jsonb where slug = 'usb-fairy-lights-10m';
update public.products set brand = 'No Brand', specs = '{"brand": "No Brand", "material": "Mixed materials", "dimensions": "5 m", "care": "Wipe clean"}'::jsonb where slug = 'rgb-led-strip-5m-remote';
update public.products set brand = 'No Brand', specs = '{"brand": "No Brand", "material": "Mixed materials", "dimensions": "Standard", "care": "Wipe clean"}'::jsonb where slug = 'aroma-candle-set-of-3';
update public.products set brand = 'No Brand', specs = '{"brand": "No Brand", "material": "Mixed materials", "dimensions": "Standard", "care": "Wipe clean"}'::jsonb where slug = 'ktm-wall-posters-set-of-6';
update public.products set brand = 'No Brand', specs = '{"brand": "No Brand", "material": "Mixed materials", "dimensions": "Standard", "care": "Wipe clean"}'::jsonb where slug = 'vinyl-wall-stickers-pack';
update public.products set brand = 'No Brand', specs = '{"brand": "No Brand", "players": "1+", "material": "Tournament-grade plastic + wood"}'::jsonb where slug = 'speed-cube-3x3-magnetic';
update public.products set brand = 'No Brand', specs = '{"brand": "No Brand", "players": "2-4", "material": "Tournament-grade plastic + wood"}'::jsonb where slug = 'family-ludo-board-game';
update public.products set brand = 'No Brand', specs = '{"brand": "No Brand", "players": "2-4", "material": "Tournament-grade plastic + wood"}'::jsonb where slug = 'magnetic-chess-set-foldable';
update public.products set brand = 'No Brand', specs = '{"brand": "No Brand", "players": "2-4", "material": "Tournament-grade plastic + wood"}'::jsonb where slug = 'waterproof-playing-cards-2-deck';
update public.products set brand = 'No Brand', specs = '{"brand": "No Brand", "players": "1+", "material": "Tournament-grade plastic + wood"}'::jsonb where slug = 'dart-board-15-inch-plus-darts';
update public.products set brand = 'No Brand', specs = '{"brand": "No Brand", "material": "Mixed materials", "dimensions": "Standard", "care": "Wipe clean"}'::jsonb where slug = 'badminton-set-2-rackets';
update public.products set brand = 'No Brand', specs = '{"brand": "No Brand", "material": "Latex", "weight": "507 g"}'::jsonb where slug = 'pro-bearing-skipping-rope';
update public.products set brand = 'No Brand', specs = '{"brand": "No Brand", "material": "TPE", "weight": "544 g"}'::jsonb where slug = 'anti-skid-yoga-mat-6mm';
update public.products set brand = 'No Brand', specs = '{"brand": "No Brand", "material": "Coated iron", "weight": "1.5 kg"}'::jsonb where slug = 'coated-dumbbell-pair-3kg';
update public.products set brand = 'No Brand', specs = '{"brand": "No Brand", "material": "Latex", "weight": "618 g"}'::jsonb where slug = 'resistance-bands-set-of-5';
update public.products set brand = 'No Brand', specs = '{"brand": "No Brand", "material": "Mixed materials", "dimensions": "Standard", "care": "Wipe clean"}'::jsonb where slug = 'vault-piggy-bank-with-lock';
update public.products set brand = 'No Brand', specs = '{"brand": "No Brand", "material": "Mixed materials", "dimensions": "Standard", "care": "Wipe clean"}'::jsonb where slug = 'led-digital-alarm-clock';
update public.products set brand = 'No Brand', specs = '{"brand": "No Brand", "material": "Mixed materials", "dimensions": "Standard", "care": "Wipe clean"}'::jsonb where slug = 'photo-frames-3-pack';
update public.products set brand = 'No Brand', specs = '{"brand": "No Brand", "material": "Mixed materials", "dimensions": "Standard", "care": "Wipe clean"}'::jsonb where slug = 'ktm-charm-keychains-set-of-5';
update public.products set brand = 'No Brand', specs = '{"brand": "No Brand", "material": "Mixed materials", "dimensions": "Standard", "care": "Wipe clean"}'::jsonb where slug = 'mini-succulent-pots-3-set';
update public.products set brand = 'No Brand', specs = '{"brand": "No Brand", "material": "Mixed materials", "dimensions": "Standard", "care": "Wipe clean"}'::jsonb where slug = 'incense-holder-plus-20-sticks';
update public.products set brand = 'No Brand', specs = '{"brand": "No Brand", "material": "Mixed materials", "dimensions": "Standard", "care": "Wipe clean"}'::jsonb where slug = 'steel-straws-4-set-with-brush';
update public.products set brand = 'No Brand', specs = '{"brand": "No Brand", "material": "Mixed materials", "dimensions": "Standard", "care": "Wipe clean"}'::jsonb where slug = 'bamboo-toothbrushes-4-pack';
update public.products set brand = 'No Brand', specs = '{"brand": "No Brand", "material": "Mixed materials", "dimensions": "Standard", "care": "Wipe clean"}'::jsonb where slug = 'cotton-handkerchiefs-6-pack';
update public.products set brand = 'No Brand', specs = '{"brand": "No Brand", "material": "Mixed materials", "dimensions": "Standard", "care": "Wipe clean"}'::jsonb where slug = 'travel-organizer-pouch-set';
update public.products set brand = 'No Brand', specs = '{"brand": "No Brand", "material": "Mixed materials", "dimensions": "Standard", "care": "Wipe clean"}'::jsonb where slug = 'foldable-laundry-bag-large';
update public.products set brand = 'No Brand', specs = '{"brand": "No Brand", "material": "Mixed materials", "dimensions": "Standard", "care": "Wipe clean"}'::jsonb where slug = 'stackable-shoe-rack-4-tier';
update public.products set brand = 'No Brand', specs = '{"brand": "No Brand", "material": "Mixed materials", "dimensions": "40 cm", "care": "Wipe clean"}'::jsonb where slug = 'mini-whiteboard-40cm-plus-markers';
update public.products set brand = 'No Brand', specs = '{"brand": "No Brand", "material": "Mixed materials", "dimensions": "27 cm", "care": "Wipe clean"}'::jsonb where slug = 'sport-frisbee-27cm';
update public.products set brand = 'No Brand', specs = '{"brand": "No Brand", "material": "Mixed materials", "dimensions": "Standard", "care": "Wipe clean"}'::jsonb where slug = 'tennis-cricket-balls-6-pack';
update public.products set brand = 'Zebra', specs = '{"brand": "Zebra", "tip": "2 mm", "pack_size": "5", "weight": "34 g"}'::jsonb where slug = 'zebra-mildliner-highlighters-5-set';
update public.products set brand = 'Tombow', specs = '{"brand": "Tombow", "tip": "2 mm", "pack_size": "10", "weight": "30 g"}'::jsonb where slug = 'tombow-dual-brush-pens-10-set';
update public.products set brand = 'No Brand', specs = '{"brand": "No Brand", "print_width": "58 mm", "connectivity": "Bluetooth", "weight": "176 g"}'::jsonb where slug = 'mini-thermal-photo-printer';
update public.products set brand = 'No Brand', specs = '{"brand": "No Brand", "material": "PP plastic", "weight": "81 g"}'::jsonb where slug = 'washi-tape-rolls-12-set';
update public.products set brand = 'No Brand', specs = '{"brand": "No Brand", "material": "Metal + plastic", "weight": "118 g"}'::jsonb where slug = 'wax-seal-stamp-kit-vintage';
update public.products set brand = 'No Brand', specs = '{"brand": "No Brand", "tip": "2 mm", "pack_size": "24", "weight": "55 g"}'::jsonb where slug = 'acrylic-marker-pens-24-set';
update public.products set brand = 'No Brand', specs = '{"brand": "No Brand", "tip": "0.5 mm", "pack_size": "9", "weight": "51 g"}'::jsonb where slug = 'muji-style-gel-pens-9-pack';
update public.products set brand = 'No Brand', specs = '{"brand": "No Brand", "size": "A5", "pages": "240", "paper": "80 GSM", "weight": "128 g"}'::jsonb where slug = 'kraft-sticky-memo-roll';
update public.products set brand = 'No Brand', specs = '{"brand": "No Brand", "size": "A5", "pages": "100", "paper": "80 GSM", "weight": "165 g"}'::jsonb where slug = 'foldable-bamboo-book-stand';
update public.products set brand = 'No Brand', specs = '{"brand": "No Brand", "size": "A5", "pages": "120", "paper": "80 GSM", "weight": "202 g"}'::jsonb where slug = 'leather-desk-pad-60cm';
update public.products set brand = 'No Brand', specs = '{"brand": "No Brand", "power": "USB 5V", "modes": "3", "weight": "356 g"}'::jsonb where slug = 'sunset-projection-lamp';
update public.products set brand = 'No Brand', specs = '{"brand": "No Brand", "power": "USB 5V", "modes": "3", "weight": "393 g"}'::jsonb where slug = 'galaxy-star-projector';
update public.products set brand = 'No Brand', specs = '{"brand": "No Brand", "power": "USB 5V", "modes": "3", "weight": "249 g"}'::jsonb where slug = 'usb-mini-humidifier-300ml';
update public.products set brand = 'No Brand', specs = '{"brand": "No Brand", "driver": "10 mm", "battery": "25 h playtime", "bluetooth": "5.3", "warranty": "6 months"}'::jsonb where slug = 'bluetooth-karaoke-mic';
update public.products set brand = 'No Brand', specs = '{"brand": "No Brand", "compatibility": "Universal", "material": "ABS + aluminium", "warranty": "6 months", "weight": "219 g"}'::jsonb where slug = 'retro-mini-game-console-400-in-1';
update public.products set brand = 'No Brand', specs = '{"brand": "No Brand", "compatibility": "Universal", "material": "ABS + aluminium", "warranty": "6 months", "weight": "95 g"}'::jsonb where slug = 'magsafe-card-wallet-leather';
update public.products set brand = 'No Brand', specs = '{"brand": "No Brand", "compatibility": "Universal", "material": "ABS + aluminium", "warranty": "6 months", "weight": "132 g"}'::jsonb where slug = 'crossbody-phone-lanyard-strap';
update public.products set brand = 'No Brand', specs = '{"brand": "No Brand", "compatibility": "Universal", "material": "ABS + aluminium", "warranty": "6 months", "weight": "169 g"}'::jsonb where slug = 'led-digital-wall-clock';
update public.products set brand = 'No Brand', specs = '{"brand": "No Brand", "compatibility": "Universal", "material": "ABS + aluminium", "warranty": "6 months", "weight": "206 g"}'::jsonb where slug = 'usb-portable-blender-450ml';
update public.products set brand = 'No Brand', specs = '{"brand": "No Brand", "power": "USB 5V", "modes": "3", "weight": "327 g"}'::jsonb where slug = 'smart-led-bulb-colour-e27';
update public.products set brand = 'No Brand', specs = '{"brand": "No Brand", "upper": "Canvas", "sole": "Anti-skid rubber", "weight": "755 g"}'::jsonb where slug = 'chunky-dad-sneakers-white';
update public.products set brand = 'No Brand', specs = '{"brand": "No Brand", "material": "Stretch denim", "fit": "Loose", "care": "Machine wash cold"}'::jsonb where slug = 'baggy-wide-leg-jeans';
update public.products set brand = 'No Brand', specs = '{"brand": "No Brand", "material": "Mixed materials", "care": "Wipe clean"}'::jsonb where slug = 'claw-clips-matte-12-set';
update public.products set brand = 'No Brand', specs = '{"brand": "No Brand", "material": "Mixed materials", "care": "Wipe clean"}'::jsonb where slug = 'silk-scrunchies-6-set';
update public.products set brand = 'No Brand', specs = '{"brand": "No Brand", "material": "Mixed materials", "care": "Wipe clean"}'::jsonb where slug = 'reversible-bucket-hat';
update public.products set brand = 'No Brand', specs = '{"brand": "No Brand", "capacity": "12 L", "material": "Water-resistant polyester", "weight": "584 g"}'::jsonb where slug = 'baguette-shoulder-bag';
update public.products set brand = 'No Brand', specs = '{"brand": "No Brand", "material": "Metal alloy", "care": "Wipe clean"}'::jsonb where slug = 'silver-chain-necklace';
update public.products set brand = 'No Brand', specs = '{"brand": "No Brand", "material": "Wool blend", "fit": "Regular", "care": "Machine wash cold"}'::jsonb where slug = 'varsity-jacket-wool-blend';
update public.products set brand = 'No Brand', specs = '{"brand": "No Brand", "material": "Cotton blend", "fit": "Regular", "care": "Machine wash cold"}'::jsonb where slug = 'cargo-mini-skirt';
update public.products set brand = 'No Brand', specs = '{"brand": "No Brand", "material": "Wool blend", "fit": "Regular", "care": "Machine wash cold"}'::jsonb where slug = 'knit-vest-sweater';
update public.products set brand = 'No Brand', specs = '{"brand": "No Brand", "capacity": "1200 ML", "material": "SS304 stainless steel", "insulation": "12 h hot / 24 h cold"}'::jsonb where slug = 'insulated-mega-tumbler-1200ml';
update public.products set brand = 'No Brand', specs = '{"brand": "No Brand", "material": "TPE", "weight": "353 g"}'::jsonb where slug = 'matcha-ceremony-set-4-piece';
update public.products set brand = 'No Brand', specs = '{"brand": "No Brand", "material": "Mixed materials", "dimensions": "Standard", "care": "Wipe clean"}'::jsonb where slug = 'crochet-tulip-bouquet';
update public.products set brand = 'No Brand', specs = '{"brand": "No Brand", "material": "Mixed materials", "dimensions": "Standard", "care": "Wipe clean"}'::jsonb where slug = 'mushroom-silicone-lamp';
update public.products set brand = 'No Brand', specs = '{"brand": "No Brand", "material": "Mixed materials", "dimensions": "Standard", "care": "Wipe clean"}'::jsonb where slug = 'mini-desk-vacuum-usb';
update public.products set brand = 'No Brand', specs = '{"brand": "No Brand", "material": "Mixed materials", "dimensions": "Standard", "care": "Wipe clean"}'::jsonb where slug = 'photo-grid-wall-with-clips';
update public.products set brand = 'No Brand', specs = '{"brand": "No Brand", "material": "Mixed materials", "dimensions": "Standard", "care": "Wipe clean"}'::jsonb where slug = 'diy-boba-tea-kit';
update public.products set brand = 'No Brand', specs = '{"brand": "No Brand", "material": "Mixed materials", "dimensions": "Standard", "care": "Wipe clean"}'::jsonb where slug = 'overnight-oats-jars-2-set';
update public.products set brand = 'No Brand', specs = '{"brand": "No Brand", "material": "TPE", "weight": "612 g"}'::jsonb where slug = 'waterproof-picnic-mat';
update public.products set brand = 'No Brand', specs = '{"brand": "No Brand", "material": "Mixed materials", "dimensions": "Standard", "care": "Wipe clean"}'::jsonb where slug = 'waterfall-incense-burner';
